### ISSUE TITLE
How to add to existing Solution?

### ISSUE THREAD

**Issue by sadhac** [enisn/Xamarin.Forms.InputKit#4]
Hi 

Can you please advise how to add this to my existing XF solution?

Thanks

**Comment by enisn** [comment]
You can add manually theese controls to your project 
https://github.com/enisn/Xamarin.Forms.InputKit/tree/master/InputKit/Shared/Controls

Or you can download the NuGet Package to your project [RECOMMENDED]

https://www.nuget.org/packages/Xamarin.Forms.InputKit/

I recommend the NuGet because there are some rendererers including the package. Nuget adds them automatically your project

**Comment by sadhac** [comment]
Thanks I have got it to work
